apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-app
    namespace: ecommerce-vti
    labels:
        app: backend-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: backend-app
    template:
        metadata:
            labels:
                app: backend-app
        spec:
            serviceAccountName: external-secrets-sa
            containers:
                - name: backend
                  image: "BACKEND_IMAGE"
                  ports:
                      - containerPort: 9000
                  env:
                      - name: APP_ENV
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: APP_ENV
                      - name: APP_DEBUG
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: APP_DEBUG
                      - name: LOG_CHANNEL
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: LOG_CHANNEL
                      - name: DB_CONNECTION
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: DB_CONNECTION
                      - name: CACHE_DRIVER
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: CACHE_DRIVER
                      - name: QUEUE_CONNECTION
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: QUEUE_CONNECTION
                      - name: SESSION_DRIVER
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: SESSION_DRIVER
                      - name: APP_KEY
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: APP_KEY
                      - name: DB_HOST
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: DB_HOST
                      - name: DB_DATABASE
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: DB_DATABASE
                      - name: DB_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: DB_USERNAME
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: DB_PASSWORD
                      - name: REDIS_HOST
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: REDIS_HOST
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                  livenessProbe:
                      tcpSocket:
                          port: 9000
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      tcpSocket:
                          port: 9000
                      initialDelaySeconds: 5
                      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    name: backend-service
    namespace: ecommerce-vti
spec:
    selector:
        app: backend-app
    ports:
        - protocol: TCP
          port: 9000
          targetPort: 9000
    type: ClusterIP
