apiVersion: v1
kind: ConfigMap
metadata:
    name: backend-config
    namespace: ecommerce-vti
data:
    APP_ENV: "production"
    APP_DEBUG: "false"
    LOG_CHANNEL: "stderr"
    DB_CONNECTION: "pgsql"
    CACHE_DRIVER: "redis"
    QUEUE_CONNECTION: "redis"
    SESSION_DRIVER: "redis"
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: frontend-config
    namespace: ecommerce-vti
data:
    NODE_ENV: "production"
    NEXT_TELEMETRY_DISABLED: "1"
