apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-app
    namespace: ecommerce-vti
    labels:
        app: frontend-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: frontend-app
    template:
        metadata:
            labels:
                app: frontend-app
        spec:
            serviceAccountName: external-secrets-sa
            containers:
                - name: frontend
                  image: "FRONTEND_IMAGE"
                  ports:
                      - containerPort: 3000
                  envFrom:
                      # Load ALL secrets from AWS Secrets Manager
                      - secretRef:
                            name: frontend-secrets
                      # Load basic config from ConfigMap
                      - configMapRef:
                            name: frontend-config
                  env:
                      # Override with K8s internal API endpoint
                      - name: NEXT_PUBLIC_API_URL
                        value: "http://backend-service.ecommerce-vti.svc.cluster.local:9000"
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 3000
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 3000
                      initialDelaySeconds: 5
                      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: ecommerce-vti
spec:
    selector:
        app: frontend-app
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: ClusterIP
