apiVersion: apps/v1
kind: Deployment
metadata:
    name: horizon-worker
    namespace: ecommerce-vti
    labels:
        app: horizon-worker
spec:
    replicas: 1
    selector:
        matchLabels:
            app: horizon-worker
    template:
        metadata:
            labels:
                app: horizon-worker
        spec:
            serviceAccountName: external-secrets-sa
            containers:
                - name: horizon
                  image: "HORIZON_IMAGE"
                  envFrom:
                      # Load ALL secrets from AWS Secrets Manager
                      - secretRef:
                            name: backend-secrets
                      # Load basic config from ConfigMap
                      - configMapRef:
                            name: backend-config
                  env:
                      # Override with K8s internal services
                      - name: DB_HOST
                        value: "postgres-service.ecommerce-vti.svc.cluster.local"
                      - name: DB_PORT
                        value: "5432"
                      - name: REDIS_HOST
                        value: "redis-service.ecommerce-vti.svc.cluster.local"
                      - name: REDIS_PORT
                        value: "6379"
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: scheduler-worker
    namespace: ecommerce-vti
    labels:
        app: scheduler-worker
spec:
    replicas: 1
    selector:
        matchLabels:
            app: scheduler-worker
    template:
        metadata:
            labels:
                app: scheduler-worker
        spec:
            serviceAccountName: external-secrets-sa
            containers:
                - name: scheduler
                  image: "SCHEDULER_IMAGE"
                  envFrom:
                      # Load ALL secrets from AWS Secrets Manager
                      - secretRef:
                            name: backend-secrets
                      # Load basic config from ConfigMap
                      - configMapRef:
                            name: backend-config
                  env:
                      # Override with K8s internal services
                      - name: DB_HOST
                        value: "postgres-service.ecommerce-vti.svc.cluster.local"
                      - name: DB_PORT
                        value: "5432"
                      - name: REDIS_HOST
                        value: "redis-service.ecommerce-vti.svc.cluster.local"
                      - name: REDIS_PORT
                        value: "6379"
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "200m"
