apiVersion: apps/v1
kind: Deployment
metadata:
    name: horizon-worker
    namespace: ecommerce-vti
    labels:
        app: horizon-worker
spec:
    replicas: 1
    selector:
        matchLabels:
            app: horizon-worker
    template:
        metadata:
            labels:
                app: horizon-worker
        spec:
            serviceAccountName: external-secrets-sa
            containers:
                - name: horizon
                  image: "HORIZON_IMAGE"
                  env:
                      - name: APP_ENV
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: APP_ENV
                      - name: APP_DEBUG
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: APP_DEBUG
                      - name: LOG_CHANNEL
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: LOG_CHANNEL
                      - name: DB_CONNECTION
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: DB_CONNECTION
                      - name: CACHE_DRIVER
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: CACHE_DRIVER
                      - name: QUEUE_CONNECTION
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: QUEUE_CONNECTION
                      - name: SESSION_DRIVER
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: SESSION_DRIVER
                      - name: APP_KEY
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: APP_KEY
                      - name: DB_HOST
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: DB_HOST
                      - name: DB_DATABASE
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: DB_DATABASE
                      - name: DB_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: DB_USERNAME
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: DB_PASSWORD
                      - name: REDIS_HOST
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: REDIS_HOST
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: scheduler-worker
    namespace: ecommerce-vti
    labels:
        app: scheduler-worker
spec:
    replicas: 1
    selector:
        matchLabels:
            app: scheduler-worker
    template:
        metadata:
            labels:
                app: scheduler-worker
        spec:
            serviceAccountName: external-secrets-sa
            containers:
                - name: scheduler
                  image: "SCHEDULER_IMAGE"
                  env:
                      - name: APP_ENV
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: APP_ENV
                      - name: APP_DEBUG
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: APP_DEBUG
                      - name: LOG_CHANNEL
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: LOG_CHANNEL
                      - name: DB_CONNECTION
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: DB_CONNECTION
                      - name: CACHE_DRIVER
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: CACHE_DRIVER
                      - name: QUEUE_CONNECTION
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: QUEUE_CONNECTION
                      - name: SESSION_DRIVER
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: SESSION_DRIVER
                      - name: APP_KEY
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: APP_KEY
                      - name: DB_HOST
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: DB_HOST
                      - name: DB_DATABASE
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: DB_DATABASE
                      - name: DB_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: DB_USERNAME
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: DB_PASSWORD
                      - name: REDIS_HOST
                        valueFrom:
                            secretKeyRef:
                                name: backend-secrets
                                key: REDIS_HOST
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "200m"
