apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-vti

resources:
    - ../../base/namespace.yaml
    - ../../base/serviceaccount.yaml
    - ../../base/configmap.yaml
    - ../../base/external-secrets.yaml
    - ../../base/database-services.yaml
    - ../../base/backend-deployment.yaml
    - ../../base/workers-deployment.yaml
    - ../../base/frontend-deployment.yaml
    - ../../base/ingress.yamlpatches:
    - target:
          kind: Deployment
          name: backend-app
      patch: |-
          - op: replace
            path: /spec/replicas
            value: 3
          - op: replace
            path: /spec/template/spec/containers/0/image
            value: 234139188789.dkr.ecr.us-east-1.amazonaws.com/de000079-ecr-repo-prod:backend-latest
          - op: replace
            path: /spec/template/spec/containers/0/env
            value:
              # Production still uses internal K8s services (same as dev)
              - name: DB_HOST
                value: "postgres-service.ecommerce-vti.svc.cluster.local"
              - name: DB_PORT
                value: "5432"
              - name: REDIS_HOST
                value: "redis-service.ecommerce-vti.svc.cluster.local"
              - name: REDIS_PORT
                value: "6379"
              - name: APP_URL
                value: "https://api.ecommerce-vti.example.com"

    - target:
          kind: Deployment
          name: horizon-worker
      patch: |-
          - op: replace
            path: /spec/template/spec/containers/0/image
            value: 234139188789.dkr.ecr.us-east-1.amazonaws.com/de000079-ecr-repo-prod:horizon-latest
          - op: replace
            path: /spec/template/spec/containers/0/env
            value:
              # Production uses same internal services as dev
              - name: DB_HOST
                value: "postgres-service.ecommerce-vti.svc.cluster.local"
              - name: DB_PORT
                value: "5432"
              - name: REDIS_HOST
                value: "redis-service.ecommerce-vti.svc.cluster.local"
              - name: REDIS_PORT
                value: "6379"

    - target:
          kind: Deployment
          name: scheduler-worker
      patch: |-
          - op: replace
            path: /spec/template/spec/containers/0/image
            value: 234139188789.dkr.ecr.us-east-1.amazonaws.com/de000079-ecr-repo-prod:scheduler-latest
          - op: replace
            path: /spec/template/spec/containers/0/env
            value:
              # Production uses same internal services as dev
              - name: DB_HOST
                value: "postgres-service.ecommerce-vti.svc.cluster.local"
              - name: DB_PORT
                value: "5432"
              - name: REDIS_HOST
                value: "redis-service.ecommerce-vti.svc.cluster.local"
              - name: REDIS_PORT
                value: "6379"

    - target:
          kind: Deployment
          name: frontend-app
      patch: |-
          - op: replace
            path: /spec/replicas
            value: 3
          - op: replace
            path: /spec/template/spec/containers/0/image
            value: 234139188789.dkr.ecr.us-east-1.amazonaws.com/de000079-ecr-repo-prod:frontend-latest
          - op: replace
            path: /spec/template/spec/containers/0/env
            value:
              # Override with production API endpoint
              - name: NEXT_PUBLIC_API_URL
                value: "https://api.ecommerce-vti.example.com"

    # Production database with persistent storage
    - target:
          kind: Deployment
          name: postgres-dev
      patch: |-
          - op: replace
            path: /metadata/name
            value: postgres-prod
          - op: replace
            path: /metadata/labels/app
            value: postgres-prod
          - op: replace
            path: /spec/selector/matchLabels/app
            value: postgres-prod
          - op: replace
            path: /spec/template/metadata/labels/app
            value: postgres-prod
          - op: replace
            path: /spec/template/spec/containers/0/env/0/value
            value: ecommerce_vti_prod
          - op: replace
            path: /spec/template/spec/containers/0/env/2/value
            value: prodpassword123
          - op: replace
            path: /spec/template/spec/containers/0/resources/requests/memory
            value: "512Mi"
          - op: replace
            path: /spec/template/spec/containers/0/resources/requests/cpu
            value: "500m"
          - op: replace
            path: /spec/template/spec/containers/0/resources/limits/memory
            value: "1Gi"
          - op: replace
            path: /spec/template/spec/containers/0/resources/limits/cpu
            value: "1000m"

    - target:
          kind: Service
          name: postgres-service
      patch: |-
          - op: replace
            path: /metadata/labels/app
            value: postgres-prod
          - op: replace
            path: /spec/selector/app
            value: postgres-prod

    - target:
          kind: Deployment
          name: redis-dev
      patch: |-
          - op: replace
            path: /metadata/name
            value: redis-prod
          - op: replace
            path: /metadata/labels/app
            value: redis-prod
          - op: replace
            path: /spec/selector/matchLabels/app
            value: redis-prod
          - op: replace
            path: /spec/template/metadata/labels/app
            value: redis-prod
          - op: replace
            path: /spec/template/spec/containers/0/resources/requests/memory
            value: "256Mi"
          - op: replace
            path: /spec/template/spec/containers/0/resources/requests/cpu
            value: "200m"
          - op: replace
            path: /spec/template/spec/containers/0/resources/limits/memory
            value: "512Mi"
          - op: replace
            path: /spec/template/spec/containers/0/resources/limits/cpu
            value: "400m"

    - target:
          kind: Service
          name: redis-service
      patch: |-
          - op: replace
            path: /metadata/labels/app
            value: redis-prod
          - op: replace
            path: /spec/selector/app
            value: redis-prod
