name: 🚀 Deploy Laravel App (Self-hosted)

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"

jobs:
    deploy:
        runs-on: self-hosted
        environment: development

        steps:
            - name: 🧱 Checkout source code
              uses: actions/checkout@v4

            - name: 🛠️ Setup server environment
              working-directory: ./backend
              run: |
                  sudo chmod +x scripts/setup-env.sh
                  ./scripts/setup-env.sh

            - name: 📥 Fetch .env from previous deployment
              run: |
                  DEPLOY_PATH="${{ vars.DEPLOY_PATH }}"
                  [ -f "$DEPLOY_PATH/.env" ] && sudo cp "$DEPLOY_PATH/.env" ./backend/.env

            - name: 📦 Install PHP dependencies
              run: |
                  cd backend
                  composer install --no-dev --optimize-autoloader

            - name: ⚙️ Optimize Laravel and generate docs
              working-directory: ./backend
              run: |
                  php artisan scribe:generate --force
                  php artisan config:clear
                  php artisan route:clear
                  php artisan view:clear
                  php artisan optimize:clear

            - name: 🎨 Install and build admin UI
              working-directory: ./backend
              run: |
                  export PATH="$HOME/.nvm/versions/node/v22.16.0/bin:$PATH"
                  pnpm install
                  pnpm build

            - name: 🗂️ Backup existing .env and storage
              run: |
                  DEPLOY_PATH="${{ vars.DEPLOY_PATH }}"
                  TEMP_PATH="/tmp/deploy-temp"
                  mkdir -p "$TEMP_PATH"
                  [ -f "$DEPLOY_PATH/.env" ] && sudo cp "$DEPLOY_PATH/.env" "$TEMP_PATH/.env"
                  [ -d "$DEPLOY_PATH/storage" ] && sudo cp -r "$DEPLOY_PATH/storage" "$TEMP_PATH/storage"

            - name: 🧹 Clean DEPLOY_PATH
              run: |
                  DEPLOY_PATH="${{ vars.DEPLOY_PATH }}"
                  sudo rm -rf "$DEPLOY_PATH"/*

            - name: 📂 Copy source code to DEPLOY_PATH
              working-directory: ./backend
              run: |
                  DEPLOY_PATH="${{ vars.DEPLOY_PATH }}"
                  sudo cp -r . "$DEPLOY_PATH"

            - name: ♻️ Restore .env and storage
              run: |
                  DEPLOY_PATH="${{ vars.DEPLOY_PATH }}"
                  TEMP_PATH="/tmp/deploy-temp"
                  [ -f "$TEMP_PATH/.env" ] && sudo cp "$TEMP_PATH/.env" "$DEPLOY_PATH/.env"
                  [ -d "$DEPLOY_PATH/storage" ] && sudo rm -rf "$DEPLOY_PATH/storage"
                  [ -d "$TEMP_PATH/storage" ] && sudo cp -r "$TEMP_PATH/storage" "$DEPLOY_PATH/storage"

            - name: 🔐 Set permissions
              run: |
                  DEPLOY_PATH="${{ vars.DEPLOY_PATH }}"
                  sudo chown -R www-data:www-data "$DEPLOY_PATH"
                  sudo chmod -R 775 "$DEPLOY_PATH/storage" "$DEPLOY_PATH/bootstrap/cache"

            - name: 🧹 Clean temporary files
              run: |
                  sudo rm -rf /tmp/deploy-temp

            - name: 📏 Show final deploy folder size
              run: |
                  DEPLOY_PATH="${{ vars.DEPLOY_PATH }}"
                  sudo du -sh "$DEPLOY_PATH"

            - name: 🔧 Run Laravel migrations and restart services
              run: |
                  DEPLOY_PATH="${{ vars.DEPLOY_PATH }}"
                  cd "$DEPLOY_PATH"
                  sudo chmod +x scripts/deploy.sh
                  ./scripts/deploy.sh

            - name: 🧹 Fix workspace permission (for next run)
              if: always()
              run: |
                  sudo chown -R $USER:$USER ${{ github.workspace }}

            - name: ✅ Deployment complete
              run: echo "🎉 Deployment completed successfully!"
